### ISSUE TITLE
Receive and normalize 5 years of PF&R data

### ISSUE THREAD

**Issue by kielejocain** [hackoregon/emergency-response#1]
- [x] Have Mark upload data to team Google Drive
 - [x] Pull data from Access
 - [x] Upload/normalize in EC2
Mark Whitaker has expressed that he is hoping to get the last five years of ER data into a sufficiently privacy-free state and get it to us by the end of the week.  That data will need to be normalized and put into our AWS database so that the rest of us can access it.

**Comment by kielejocain** [comment]
I should probably take point on the receiving of the data, at least in terms of communicating with Mark and letting interested parties know when he's done.

**Comment by kielejocain** [comment]
Mark has uploaded the data!

https://drive.google.com/open?id=0B8q4DSMi3du4Z2luR0Q2RjNUc3c

**Comment by russellgould** [comment]
Hooray! I'll get started on checking it out and working on uploading it to the DB.

**Comment by russellgould** [comment]
I assigned myself since I'll be doing the normalizing.
