### ISSUE TITLE
Discuss the story we want to tell

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#11]
My impression of the 'cards' tool is that it's going to be well-suited to telling a sequential story about some particular space of data. I think we should discuss what that story might be for our team.

In our case, we already know some things we can include in that story such as:
* the surprising ratio of fire calls vs. health calls for PF&R (~3/4ths of the 70-80k calls per year)
* that the new fire chief is interested in seeing the fire dept more as a public health organization, rather than strictly fire management

What else do we have to say? What else have we found interesting? What would the people of Portland, and Oregon in general, like to hear?

**Comment by hannahkane** [comment]
Things that might be of interest to Fire bureau and the public: 
* Are areas served equitably?
 * Response times laid over demographics?

**Comment by meganmckissack** [comment]
- visualizing how many responses are medical rather than fire
- how many of these are related to homelessness

**Comment by hannahkane** [comment]
Closing in lieu of product statements on the wiki
