### ISSUE TITLE
Compute population density metrics

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#23]

**Comment by kielejocain** [comment]
Blocked by #4 

Edit: As #4 has been broken into tasks, this is now blocked by #38

**Comment by kielejocain** [comment]
@futurechris Do we want this by something other than census block?  FMA, perhaps?

**Comment by futurechris** [comment]
If we're able to do FMA, and maybe fire block, I think those would both be good.

I understand there's been a bit of trouble with finding a principled and statistically valid/reasonable way to map from census block to FMA. There are "objective" approaches, but they aren't going to produce great data.

My guess is we'll have to just pick something and go with it, then thoroughly document our assumptions and likely effects of our decisions. May be the best we can do.

**Comment by kielejocain** [comment]
Handled in https://github.com/hackoregon/emergency-response/commit/7ec6bf3858ed0c18956e5a0cb3deee9a8907e16e.  (cf. [census_eda_geo.ipynb](https://github.com/hackoregon/emergency-response/blob/analytics/notebooks/census_eda_geo.ipynb))
