### ISSUE TITLE
Compute various time roll-ups

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#28]
Incidents by hour/day of week/time/moon phase/holiday

**Comment by kielejocain** [comment]
Blocked by #1

**Comment by hannahkane** [comment]
@qingdatascience is going to start working on this :)

**Comment by qingdatascience** [comment]
I found the sql scripts for moon phase https://mudlthru.wordpress.com/tag/sql-datetime/  and  holidays  http://www.joebooth-consulting.com/sqlServer/sqlServer.html#CalendFunc   Not sure how to insert into my query.

**Comment by qingdatascience** [comment]
Finished exploratory analysis, uploaded Notebook.
