### ISSUE TITLE
Consider other data sources

### ISSUE THREAD

**Issue by kielejocain** [hackoregon/emergency-response#3]
Are there any other bits of data (e.g. census, weather, events) that we want to include in the analytics?

**Comment by kielejocain** [comment]
Any way to capture lack of fire/CO alarms?  Can we say (with data) how important those issues might be?

**Comment by hannahkane** [comment]
Real estate and/or zoning data about age of buildings

**Comment by kielejocain** [comment]
It seems the consensus that we'll get census and zoning data, but not weather or events.  Also, Mark is going to ask if PF&R have access to smoke/CO alarm distribution.  I'm closing this and opening other tickets for the individual tasks.
