### ISSUE TITLE
Create branch for vagrant box

### ISSUE THREAD

**Issue by russellgould** [hackoregon/emergency-response#33]
Need to merge my personal repo containing the vagrant boxed version of our db into a new branch here for accessibility.

**Comment by russellgould** [comment]
Should be all done, I've moved this issue into "for review" if someone or a few people could try cloning my fork to see if the vagrant box works on their systems. https://github.com/russellgould/emergency-response/tree/vagrant_testbox

**Comment by BrianHGrant** [comment]
I followed the steps, downloaded the database as directed, and was able to boot up the box without problem, I am on a MacBook Pro with El Capitan. The database opened fine for me with pgadmin3 and information provided.

**Comment by russellgould** [comment]
Awesome, thanks for checking it! I also booted it up on a Windows system myself and it went fine, but I'm still not entirely sure how to merge this branch/repo into the main one so I'll leave the issue open for now until it's merged.

**Comment by BrianHGrant** [comment]
I submitted a PR for a small update to the box on your fork. It will open up a port to forward to host box. It makes it easier to interact with the API.

**Comment by russellgould** [comment]
Finally added a branch for this, and put in a pull request to merge my working repo into the new branch. I checked that the box works with the new uploaded DB as of today (in the shared drive "fire_db_2010") which we should be getting up on the AWS instance soon™.
