### ISSUE TITLE
figure out how to get Code to Scene column

### ISSUE THREAD

**Issue by hannahkane** [hackoregon/emergency-response#39]
cc @markawhitaker

**Comment by markawhitaker** [comment]
@hannahkane I misspoke on this last night. The code to scene field is already included in the Responder table, which makes sense: for each incident and responderunit, there is a corresponding code to scene. I'll follow up with a description of what the values in the codetoscene field represent.

**Comment by hannahkane** [comment]
Great. Thanks, @markawhitaker. Going to close this ticket. Let's maintain all descriptions of the data in #40 moving forward.

**Comment by kielejocain** [comment]
I'll be sure to add this to the data dictionary #40
