### ISSUE TITLE
Collect other data sources

### ISSUE THREAD

**Issue by kielejocain** [hackoregon/emergency-response#4]
Once the other data sources have been identified, they should be sourced, normalized, and put in a place that our team/APIs can access them.

Blocked by #3

**Comment by futurechris** [comment]
Beyond census data - are there any more-frequently updated sources out there that anyone knows about?

Zillow?

**Comment by hannahkane** [comment]
Wondering if we can close this in light of #38 and #41? Any objections?

**Comment by kielejocain** [comment]
That's fine with me.  I'll update the blockage for 21-24 as well.
