### ISSUE TITLE
Collect City of Portland Zoning Data

### ISSUE THREAD

**Issue by kielejocain** [hackoregon/emergency-response#41]
As we have decided to attempt to use zoning data, and as Ryan has suggested he can get it, here's an issue we can close when it's done.

**Comment by markawhitaker** [comment]
If you're looking for shapefiles on this, I believe we can provide them. Ryan should just contact our GIS analyst.

**Comment by rcallihan** [comment]
The zoning shapefile is on our googledrive. Downloaded from CivicApps. https://drive.google.com/open?id=0B_RZuApNRm5uM0dyUjJfNkpubEE

**Comment by rcallihan** [comment]
I've uploaded a newer version that has more standardized zoning.
