### ISSUE TITLE
no beer

### ISSUE THREAD

**Issue by flamingveggies** [hackoregon/emergency-response#56]
why do the other groups always seem to have beer?

**Comment by hannahkane** [comment]
what kind of beer do people like?

**Comment by hannahkane** [comment]
also, if anyone is uncomfortable with a beer-y environment, please feel free to let me know in a private chat.

**Comment by hannahkane** [comment]
![beer](https://cloud.githubusercontent.com/assets/8389648/23242709/3eb9ab6e-f92f-11e6-8e22-685b158ee452.JPG)
