### ISSUE TITLE
Does the data change interestingly with time?

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#57]
Analytics question from product team.

**Comment by qingdatascience** [comment]
I split the incident counts by year. They have similar pattern, just get bigger. If we need to check the aggregation of travel time and on-scene time by year, I can do it later.

**Comment by qingdatascience** [comment]
I checked the Response_Time and OnScene_Time from 2010 to 2016. Response_Time did not change very much, but OnScene_Time seems to get shorter each year.  I uploaded the notebook containing the analysis and plot. I will close this ticket for now.

**Comment by futurechris** [comment]
Oops, I meant to reply to this. I looked through your notebook last week, looks great. It's nice to see some data plotted, so we can start to get an idea of what the data contains (even if it's 'exactly what we would expect').

I had two comments I wanted to leave:
* Should we be normalizing?
* Did you check whether results were different when you split by incident type (fire vs. medical)?

----

For normalization: We might want to normalize some data, especially on related to months.

I.e., in the "number of incidents on a given day of the month" chart, we see that 31 is by far the lowest, which makes sense: Many months don't have a 31st day. Similar situation for 30th, since February never has a 30th day.

So perhaps we could normalize those?

Similarly for counts-by-month. Since February is always the shortest month, it will tend to look like it has fewer incidents.

Probably, we'll want to spend some time as a team figuring out what sorts of data to normalize, when, and how. We need to be careful not to introduce bias or artifacts when doing so.

----

As for comparing fire and medical, I think it might help us uncover and tell a story. These kinds of time/date-related stats are easy to digest for most people (I think :)), and would work well for infographics and simple charts.

E.g., there's good reason to expect that there are more fires on/around the 4th of July. Is this also true of medical calls? (Seems a bit likely to me - many people injuring themselves doing reckless things.)

**Comment by datascienceqing** [comment]
Good suggestions. I will look into it.

**Comment by qingdatascience** [comment]
I updated the time rollup notebook. Just check the fire and medical incidents in different months, I normalized by number of day for different months.
