### ISSUE TITLE
Define approach for basing GIS/shapefile data

### ISSUE THREAD

**Issue by sky-t** [hackoregon/emergency-response#6]
Although we have put the initial dispatch data samples from PF&R into the AWS fire database, we have not loaded the shapefiles also received and QA'd by Ryanc. To my understanding, we are holding off on loading any files pending a decision on whether Hack OR will go with a centralized store of GIS data supporting all teams, or a decentralized approach where each team will maintain their own store of GIS data. Once this decision is made, several shape tables are ready to load.

**Comment by znmeb** [comment]
The last I heard from Sanjuro, we are building an AWS PostgreSQL / PostGIS instance for each project specifically so the teams can upload data. So if you have shapefiles, talk to Sanjuro in Slack. 

If we later see a need to centralize it is not difficult to merge tables / databases from separate PostGIS instances into a single one, but it is a task that will take effort from a person. ;-)

**Comment by kielejocain** [comment]
As we have built a DB locally and there is no appetite for a central version, we can close this.
