### ISSUE TITLE
Explore what good options are for displaying FMAs/other geo data in a Python notebook

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#62]
Just something to easily display data, for exploration.

Ideally it would be able to work with data from the DB or local stuff, dataframes, etc.

**Comment by rcallihan** [comment]
Scott and I are tag teaming this. The idea is to find something easy to use that allows us spatially explore a variety of variables associated with the Fire Block or FMA. Our criteria is to find a library/method that allows for: 

- Choropleth map display in a notebook. Ideally, the category/binning of color values in the display would be an easy set up. 
- Easy installation within our current python environment. 
- Works well with pandas data frames.

**Comment by sky-t** [comment]
Merged a notebook into the analytics branch that test runs geopandas and geoplot for mapping. I think it's a pretty cool toolset and meets the criteria that Ryan listed (the catch is that it doesn't seem to run on python 3.6 yet so I had to create a 3.5 kernel to run it in Jupyter: https://github.com/hackoregon/emergency-response/blob/analytics/notebooks/census_eda_geo.ipynb

**Comment by sky-t** [comment]
I think we've demonstrated that geopandas works pretty well for this purpose. Closing this issue out.
