### ISSUE TITLE
PF&R Performance Dashboard

### ISSUE THREAD

**Issue by futurechris** [hackoregon/emergency-response#7]
Notes from the meeting on 12/21/2017 with PF&R's Mark Whitaker indicated that a sort of "performance dashboard" would be one of the things that PF&R is most interested in.

Per Ryanc's notes:
* The dashboard would breakdown metrics into meaningful geographic units (FMA's (Fire Management Area), Fire Blocks)
  * Mostly concerned with response time for high priority medical calls and actual fire emergencies.

I think that targeting this for demo day could be a bit on the ambitious side given our schedule, but it's also potentially quite interesting.

Sorting questions and tasks vaguely into "Data", "Analysis", and "Front End", what do we need to know and do to make this?

To start:

**Data:**
* Is the data we're getting from PF&R in an appropriate form to make this work?
* Do we need to source additional data to make this work? 
  * E.g., do we know the outlines of fire blocks/FMAs?
* ...

**Analysis:**
* Are there any objections to just using Python for this?
* What is the shape of the output that the front end needs?
* Is the transformation straightforward? (Binning locations, census look-ups, etc.)
* ...

**Front End:**
* Is such a dashboard appropriate for the shared platform tool we're aiming to use? (Cards)
* What features are there, and which most critical?
* Is there low-hanging fruit (MVP variety) we could pursue quickly?
* ...

I think more questions will come up if/when we pursue this project, but I wanted to get something started.

**Comment by rcallihan** [comment]
This seemed to be the big ticket item that was most useful to PF&R. We should definitely put thought into pursing it. 

If we keep the metrics simple, the analysis side is mostly straightforward - ie aggregating values from smaller areas (fire blocks, census tracts/blocks) into larger areas (Fire Management Areas). 

Though before pursuing, we should talk with the front-end to see what's reasonable given the time constraints and the strengths/limitations of the card system. 

Chris, I'm happy to help answer some of your initial questions and also help think of more concerns/questions at tonight's standup.
