### ISSUE TITLE
Get incident rates for each FMA

### ISSUE THREAD

**Issue by hannahkane** [hackoregon/emergency-response#72]
For Fire, it should be # of incidents per household, and per sq mile
For Medical, it should be # of incidents per capita, and per sq mile

We'll use this to compare response times across FMAs

**Comment by sky-t** [comment]
I'll calculate metrics for 3 incident categories: Medical, everyone non-Medical, and FIRE/EXPLOSION incidents only (excluding the other non-medical categories).

**Comment by futurechris** [comment]
Believe this is complete, now.
