### ISSUE TITLE
Write queries to create demographic rollup tables by FMA

### ISSUE THREAD

**Issue by hannahkane** [hackoregon/emergency-response#75]

**Comment by sky-t** [comment]
Per discussion with @BrianHGrant, I'll put all demographic rollup data into a single table that can be hit by the API. @futurechris will also add the response time rollups to this table.

**Comment by sky-t** [comment]
@BrianHGrant @futurechris , I created a new table named `fma_api_rollup` in the db and have started populating it with demographic data by FMA. I have median response time by FMA and will add that as well.

**Comment by sky-t** [comment]
`fma_api_rollup` table is now populated with the following demographic data:  total population, % owner occ, % renter occ, median hh income, % with health ins, % w/o health ins, % college grad or higher, % rec food snaps, % nonwhite, % below pov line, % hh w/ member 65+, % in diff area last year

**Comment by BrianHGrant** [comment]
Thanks, was able to inspect the tables and looking good. Will have endpoint created shortly
