### ISSUE TITLE
Database Data types for fma.fma/fm_api_rollup.fma 

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/emergency-response#88]
So I believe the fma number (fma column) in these tables is saved as a char field. As such if someone searches for fma 1 vs fma 01 , they will be returned "not found". Can we change these to number fields so the leading 0 will not affect searches?

**Comment by sky-t** [comment]
I'll fix this!

**Comment by sky-t** [comment]
@BrianHGrant, converted the fma column to integer in the fma_api_rollup table. Let me know if you need anything else.

**Comment by BrianHGrant** [comment]
@sky-t ,The fma.fma column needs to be changed to integer as well, causing an error when doing a join.

**Comment by sky-t** [comment]
Sorry bout that. Check it again.
